### ISSUE TITLE
Share to Facebook not working

### ISSUE THREAD

**Issue by junogueira** [stefanobartoletti/nuxt-social-share#175] opened 2024-05-26 13:58 UTC
Sharing to Facebook is not working, even on https://stefanobartoletti.github.io/nuxt-social-share.

Maybe they changed the URL for sharing? Didn't find anything on their docs yet.

**Comment by stefanobartoletti** [comment] 2024-05-26 19:13
I cannot reproduce this, especially not by pinpointing the issue to facebook.

I checked and the demo at https://stefanobartoletti.github.io/nuxt-social-share/ is not using the correct URL and it is trying to share links with `localhost`, so in example the share URL is something like `https://www.facebook.com/sharer/sharer.php?u=http://localhost/nuxt-social-share` but for ALL networks, not just Facebook.

I will try to have a look and see what's going on there, but this is just a demo and really a 100% reliable implementation. 

You can see a "real world" live example here (scroll down to the end of the article), I tested and the share buttons are all working as expected, both on desktop and on mobile.

It would be helpful if you can provide more details about your specific implementation, with a minimal reproducible demo, and the environment where this issue is happening to you (OS, Browser, etc.)

**Comment by stefanobartoletti** [comment] 2024-05-29 10:55
I'm not sure what is happening here, I can see from your screens that you are always having a "localhost" shared, even  on https://nuxt-storyblok-starter.netlify.app/blog/article-8/, where it should use instead the correct URL.

About your own example, I see that you are using it on your own local development server on `localhost:3000`, so of course you are not able to share it on any social, because your local environment is not accessible to the web.

You should try to publish it online on some hosting platform and see if this still happens on your own implementation, and maybe share the details of the server (hosting platform, specific configuration, and so on)

Anyway, for what I can see, this seems to be related to how the current URL is retrieved internally, but at the moment I cannot give a solution, this has to be investigated further.

**Comment by stefanobartoletti** [comment] 2024-05-29 17:44
I opened a more generic issue here #177 , if you want to follow.

**Comment by junogueira** [comment] 2024-05-29 17:48
Thanks for checking the issue, Stefano.

**Comment by stefanobartoletti** [comment] 2024-06-09 17:00
Closing this and continuing in the more generic #177

**Closed by stefanobartoletti** 2024-06-09 17:00 UTC
Labels: bug, duplicate
